### ISSUE TITLE
UnknownMethodError: Method is not implemented for getAttribute() and isDisplayed()

### ISSUE THREAD

**Issue by KsenyLa** [react-native-windows/selenium-appium#147]
Hello, I am running tests written in typescript for native Android and iOS applications ("node" -v 14.15.4, "typescript" -v 4.5.2, "selenium-appium" -v 1.0.2, "selenium-webdriver" - v 4.1.1, "appium" -v 1.22.2)

But for methods  `getAttribute()` and `isDisplayed()` I got an error "Method is not implemented":
```
await driver.startWithCapabilities(config.capabilities);
const element = By2.nativeAccessibilityId('Scroll Up');
const attribute = await element.getAttribute('class');
```
I've tried different elements and attributes, but got the same error for Android and iOS devices.
(Also, similar error is thrown for `isDisplayed()` method)

From Appium logs: "Encountered internal error running command: NotImplementedError: Method is not implemented"

Some other methods, like: `await element.click();` or `await element.getText();` give correct results.

It looks like this is "Selenium 4" related error, since `getAttribute()` and `isDisplayed()` give correct results with "selenium-webdriver" v 3.0.6, but not with version 4.
Is there support of Selenium 4?

**Comment by licanhua** [comment]
It's verified in ^4.0.0-alpha.8 in https://github.com/react-native-windows/selenium-appium/blob/5e950ab153e5e81a9eed1185bf238070714212af/package.json#L31

And here is the code When I call selenium-webidriver's isDisplayed: 
https://github.com/react-native-windows/selenium-appium/blob/5e950ab153e5e81a9eed1185bf238070714212af/src/by2.ts#L91

Here is the document of [selenium-webdriver](https://www.selenium.dev/selenium/docs/api/javascript/module/selenium-webdriver/), so you have to figure it out by yourself.
Welcome the PR if you can fix the problem.
