### ISSUE TITLE
如何发送“鼠标右键单击”命令？

### ISSUE THREAD

**Issue by s0521** [react-native-windows/selenium-appium#148]
作者您好，

该如何实现发送“鼠标右键单击”命令呢？
contextClick

我找不到如何实现鼠标右键单击的命令。
我尝试了driver.actions().contextClick(元素)命令，但是软件界面毫无反应。

selenium中关于driver.actions().contextClick(元素)命令的说明超链接：
https://www.selenium.dev/selenium/docs/api/javascript/module/selenium-webdriver/lib/input_exports_Actions.html

我注意到“微软”的“WinAppDriver”似乎是支持“鼠标右键单击”的：
https://github.com/microsoft/WinAppDriver/blob/master/Tests/WebDriverAPI/Mouse.cs，代码的第77行。

似乎selenium、WinAppDriver都在理论上是支持的“鼠标右键单击”，但我不知道该如何通过你的工具实现这一功能，您能给出一点示例，或者给出一些帮助提示么？

提前致谢，
s0521

**Comment by licanhua** [comment]
看来需要perform
你可以执行[https://github.com/microsoft/WinAppDriver/blob/master/Tests/WebDriverAPI/Mouse.cs，代码的第77行。](https://github.com/microsoft/WinAppDriver/blob/master/Tests/WebDriverAPI/Mouse.cs%EF%BC%8C%E4%BB%A3%E7%A0%81%E7%9A%84%E7%AC%AC77%E8%A1%8C%E3%80%82) 看她发出来的消息长什么样。
从https://github.com/microsoft/WinAppDriver/blob/master/Docs/SupportedAPIs.md 看， actions是不支持的。
你可以在产品中加一个按钮，点击的时候触发右键菜单

**Comment by s0521** [comment]
我似乎水平太菜了，我不会你所说的这些操作。。。。。。。
我不知道该如何直接执行“WebDriverAPI/Mouse.cs”中的命令，也不会在产品中“增加一个按钮”，
你可以给出一个简单的演示么？
感谢~！

**Comment by licanhua** [comment]
可能最接近的是WebDriver.execute。他的代码在

https://github.com/SeleniumHQ/selenium/blob/b3f9d377d04dcefb5bfbc6fbdaffccf946bfedda/javascript/node/selenium-webdriver/lib/webdriver.js#L253


https://github.com/react-native-windows/selenium-appium/blob/5e950ab153e5e81a9eed1185bf238070714212af/src/Driver.ts#L43

可能
···
const webdriver = abc
...
webdriver.execute(command)
···
