### ISSUE TITLE
Incompatible with latest releases of appium-windows-driver

### ISSUE THREAD

**Issue by jaimecbernardo** [react-native-windows/selenium-appium#39]
The latest release of `appium-windows-driver` (`1.15.0`) seems to be incompatible with `selenium-appium`.

Trying to start the driver causes `appium` to go into a loop with this error:
```
[BaseDriver] The following capabilities were provided, but are not recognized by Appium:
[BaseDriver]   browserName
```

I've submitted a fix for this in: https://github.com/appium/appium-windows-driver/pull/88

However, after the fix, there's still at least another error to be fixed, where `appium` goes into a loop with the error:
```
[WinAppDriver] No old WinAppDrivers seemed to exist
[WinAppDriver] Spawning WinAppDriver with: 4723/wd/hub
[WinAppDriver] [STDOUT] Windows Application Driver listening for requests at: http://127.0.0.1:4723/wd/hub
[debug] [WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:4723/wd/hub/status] with no body
[WinAppDriver] [STDOUT]
[WinAppDriver] [STDOUT] Address 'http://127.0.0.1:4723/wd/hub' is already in use
[WinAppDriver] [STDOUT]
[WinAppDriver] [STDOUT] Failed to initialize: 0x80004005
[WinAppDriver] WinAppDriver exited unexpectedly with code 2147500037, signal null
```

I suspect this may be due to some port scanning logic changes in `appium-windows-driver`, but I haven't looked into it in detail.

In the meanwhile, the current workaround I'm using is forcing `appium` to use the latest version of `appium-windows-driver` I know is compatible (`1.13.0`). This can be achieved by adding the following to `package.json` and running `yarn`:
```
  "resolutions": {
    "appium/appium-windows-driver": "1.13.0"
  }
```

**Comment by licanhua** [comment]
I will take a time to update all packages to the latest version. Thanks to report it.

**Comment by licanhua** [comment]
Look like this problem is fixed by someone else, and WinAppDriver port is changed to 4724.
```
[WinAppDriver] Spawning winappdriver with: 4724/wd/hub
```

If you still hit problem, you can skip appium and use this command directly.

"C:\Program Files (x86)\Windows Application Driver\WinAppDriver.exe" 127.0.0.1 4723/wd/hub

**Comment by jaimecbernardo** [comment]
Thank you @licanhua ,
I can confirm the latest release fixed my issue!
Closing this issue.
