### ISSUE TITLE
How to interact with child window screen along with Parent?

### ISSUE THREAD

**Issue by singhrajkr** [react-native-windows/selenium-appium#48]
@licanhua 
I have seen the solution using Java winappdriver but not using selenium-appium.

My requirement is - 

When I interact with the parent application screen new child screen gets popup and I have to interact with that too and then parent app.

`describe("RHAM Test Suite", function () {
  before(() => {
    const appId = "ActualAppId";
    const capabilites = windowsAppDriverCapabilities(appId);
    return driver.startWithCapabilities(capabilites);
  });

  // Parent app windows
  it("Get RHAM App Title", async function () {
    let rhamTitle = await RHAMPage.getTitleBar();
    expect(rhamTitle).equal('Remote Hardware Access');
  });

  it("Restart WebSocket Client", async function () {
    await RHAMPage.clickRestarWebSocket();
  });

  // New Child app windows
  it("Clear SignalRClient", async function () {
    await RHAMPage.clearClientScreen();
  });
});`

**Comment by licanhua** [comment]
What do you mean child app, another window process, or just another Window in the same app?
You can find the document about [JavaScript WebDriver API](https://www.selenium.dev/selenium/docs/api/javascript/module/selenium-webdriver/index_exports_WebDriver.html).

If you are talking Window, It's possible you are looking for:
this.getWindowHandle() → Promise<string>
this.getAllWindowHandles() → Promise<Array<string>>

If you are launching child process, it's possible to start another session with appId = "Root", then search for the element.

It's more easy to communicate if you knows which [endpoint](https://github.com/SeleniumHQ/selenium/wiki/JsonWireProtocol#command-summary) your java client hit.

**Comment by singhrajkr** [comment]
just another Window in the same app @licanhua

**Comment by sm-will** [comment]
I feel like `driver.getAllWindowHandles()` should provide these, but the returned array is always empty for me.
The workaround that I'm using is do use a root driver to find a window by name.
I'm not in love with it - as finding a window from root takes 5-10 sec, but it is working on my multi-window application.

I have this helper:
``` js
import { By2, WebDriver2, windowsAppDriverCapabilities } from "selenium-appium"
let rootDriver

export const getWindowDriver = async (name) => {
  // first request will create a root driver  
  if (!rootDriver) {
    rootDriver = new WebDriver2()
    await rootDriver.startWithCapabilities(windowsAppDriverCapabilities("Root"))
  }

  const item = By2.nativeName(name, rootDriver)
  const hexId = parseInt(
    await item.getAttribute("NativeWindowHandle")
  ).toString(16)
  const driver = new WebDriver2()
  await driver.startWithCapabilities({
    browserName: "",
    platformName: "windows",
    deviceName: "WindowsPC",
    appTopLevelWindow: hexId,
  })

  return driver
}
``` 

and then tests can request window drivers with this:
``` js
// do something that opens a window called "MyApp Settings"
const settingsDriver = await getWindowDriver("MyApp Settings")
await By2.nativeName("edit button", settingsDriver).click()
```
