### ISSUE TITLE
Imports broken on case sensitive file system

### ISSUE THREAD

**Issue by thdk** [react-native-windows/selenium-appium#50]
As mentioned already in #9 some imports are using wrong casing when importing modules.

Filenames for _Driver_, _Config_ and _WinAppDriver_ are in _PascalCasing_ while _pageobject_ and _by2_ are in lowercase.

**Comment by licanhua** [comment]
Is it possible for you to create a pull request? I'm using windows and it's not case sensitive

**Comment by thdk** [comment]
@licanhua of course I'm on it.
Would you be interested in a PR to add eslint to avoid these errors in the future?

**Comment by licanhua** [comment]
sure

**Comment by licanhua** [comment]
Thanks. I just published 1.0.1 package. and please let me know if there is any problem
