### ISSUE TITLE
Unrecognized command: actions

### ISSUE THREAD

**Issue by shirvak** [react-native-windows/selenium-appium#56]
Hello, I am running on windows with the following package versions:

```json
"@types/selenium-webdriver": "^4.0.11",
"selenium-appium": "^1.0.2",
"selenium-webdriver": "^4.0.0-alpha.8",
"winappdriver": "0.0.7"
```

I have the following code:

```js
await driver.actions().move({x:400,y:540}).perform();
await driver.actions().click();
```

I get the following error:

```
UnknownCommandError: Unrecognized command: actions
```

**Comment by licanhua** [comment]
I guess WinAppDriver doesn't support it. You can check the actual message sent to WinAppDriver, then check these two documents:
https://github.com/microsoft/WinAppDriver/blob/master/Docs/SupportedAPIs.md
https://www.selenium.dev/selenium/docs/api/javascript/module/selenium-webdriver/lib/input_exports_Actions.html#mouse

WinAppDriver doesn't support all endpoints WebDriver provided.
