### ISSUE TITLE
Package doesn't work on a case sensitive filesystem

### ISSUE THREAD

**Issue by Multiply** [react-native-windows/selenium-appium#9]
Imports like https://github.com/react-native-windows/selenium-appium/blob/43e59c9a600fe8e8c035a8d6311d77f3044c1b48/src/index.ts#L8  doesn't work, as the file is named with all lowercase `by2.ts`, and not `By2.ts`

Other imports/exports have the same problem.

**Comment by licanhua** [comment]
Thank you for reporting this. I already fixed it. Reopen it if you still see this.

**Comment by Multiply** [comment]
Thanks a lot. :D
